id: gin-bfc8ca2
project: gin
language: go
source: /src/gin
task_description:
  crash_report:
  - reports/issue.md
  bug_description:
scripts:
  build: scripts/build.sh
  run: scripts/run.sh
  test: scripts/test.sh
files:
  patch: diffs/patch.diff
  poc:
  - pocs/poc.go
  future_test: diffs/test.diff
  security_test: diffs/security_test.diff
  intent_test:
sanitizer:
type: CWE-290 - Authentication Bypass by Spoofing (or IP Spoofing)
binary:
trigger_commit: f3de8132c5d955784deeadb9bcf5752e9fdf0d8c
patch_commit: bfc8ca285eb46dad60e037d57c545cd260636711
reference:
- https://github.com/gin-gonic/gin.git
- https://github.com/gin-gonic/gin/issues/2473
- https://github.com/gin-gonic/gin/commit/bfc8ca285eb46dad60e037d57c545cd260636711
originality: Publicly Available
