id: generic-c-cpython-py_pr_102397
project: cpython
language: c
source: /src/cpython
task_description:
  issue: ""
  crash_report:
    - reports/issue.md
  bug_description:
scripts:
  build: scripts/build.sh
  run: scripts/run.sh
  test: scripts/test.sh
files:
  patch: diffs/patch.diff
  future_test: diffs/test_rich.diff
  poc:
    - pocs/poc.py
sanitizer: address
type: Race Condition
binary: python
trigger_commit: 8bf8e3d9a001f1d955a9f0875ac5a70f6d5a5f5c
patch_commit: 7905ae7b1a347a5dd15174f7e44bb67c4cdb5972
reference:
- https://github.com/python/cpython.git
- https://github.com/python/cpython/pull/102528
- https://github.com/python/cpython/issues/102397
- https://github.com/python/cpython/commit/8bf8e3d9a001f1d955a9f0875ac5a70f6d5a5f5c
- https://github.com/python/cpython/commit/7905ae7b1a347a5dd15174f7e44bb67c4cdb5972
