export { Dock } from "./Dock"
export type { DockProps, DockPanelProps, TabPosition, ResizeConfig } from "./Dock"
export { DockProvider, useDock, useActivePanelId } from "./DockContext"
export { DockTabBar } from "./DockTabBar"
export type { DockTab } from "./DockTabBar"
