id: xz-69c6093
project: xz
repository: https://github.com/ulikunitz/xz
language: go
source: /src/xz
task_description:
  crash_report:
  - reports/issue.md
  bug_description:
scripts:
  build: scripts/build.sh
  run: scripts/run.sh
  test: scripts/test.sh
files:
  patch: diffs/patch.diff
  poc:
  - pocs/poc.go
  future_test: diffs/test.diff
  intent_test:
sanitizer:
type: Integer Overflow
binary:
trigger_commit: 067145b4480ef600b25a0403f386ea25ffe42fd5
patch_commit: 69c6093c7b2397b923acf82cb378f55ab2652b9b
reference:
- https://github.com/ulikunitz/xz.git
- https://github.com/ulikunitz/xz/commit/69c6093c7b2397b923acf82cb378f55ab2652b9b
- https://github.com/ulikunitz/xz/issues/35
originality: crafted
