id: RUSTSEC-2021-0031
project: "nano-arena"
repository: https://github.com/bennetthardwick/nano-arena
language: "rust"
source: "/src/nano-arena"
task_description:
  crash_report:
    - reports/issue.md
scripts:
  build: scripts/build.sh
  run: scripts/run.sh
  test: scripts/test.sh
files:
  patch: diffs/patch.diff
  future_test: diffs/test.diff
  poc:
    - pocs/src/main.rs
sanitizer: address
type: "UAF"
binary: RUSTSEC-2021-0031
trigger_commit: 1ba84c2a1b2b38653fe9a28de4a5c3d6ad6483f7
patch_commit: 6b83f9d0708337a9f8b709c1624a8587021ceba2
reference:
  - https://rustsec.org/advisories/RUSTSEC-2021-0031.html
  - https://github.com/bennetthardwick/nano-arena/issues/1
