id: docconv-b19021a
project: docconv
language: go
source: /src/docconv
task_description:
  crash_report:
  - reports/issue.md
  bug_description: none
scripts:
  build: scripts/build.sh
  run: scripts/run.sh
  test: scripts/test.sh
files:
  patch: diffs/patch.diff
  poc:
  - pocs/poc.go
  future_test: diffs/test.diff
sanitizer: none
type: CWE-78 - OS Command Injection
binary: none
trigger_commit: 44d673994791482c8aec902e0f949c354ce8dc0f
patch_commit: b19021ade3d0b71c89d35cb00eb9e589a121faa5
reference:
- https://github.com/sajari/docconv.git
- https://github.com/sajari/docconv/commit/b19021ade3d0b71c89d35cb00eb9e589a121faa5
- https://vuldb.com/?id.216502
originality: Self Craft