"""Generated regions in hand-written Markdown pages.

A reference page is Markdown written by hand, with regions that a generator owns:

    <!-- generated: cli run -->

    ...

    <!-- end generated -->

A generator returns the content of its regions by name. Filling a page replaces the body of each
region and keeps everything outside the regions, so prose stays next to the tables it explains.
"""

from __future__ import annotations

import difflib
import re
from collections import Counter
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]

REGION = re.compile(r"<!-- generated: (?P<name>[^>]+?) -->\n.*?<!-- end generated -->", re.DOTALL)


class PageError(Exception):
    """A page does not have exactly the regions its generator produces, or a source is invalid."""


@dataclass(frozen=True)
class Page:
    name: str
    path: Path
    """Relative to the repository root."""
    regions: Callable[[], dict[str, str]]
    """Content of every region of the page, by name."""

    def fill(self, text: str) -> str:
        regions = self.regions()
        found = Counter(m["name"] for m in REGION.finditer(text))
        problems = [f"region {name!r} appears {n} times" for name, n in found.items() if n > 1]
        problems += [f"missing region {name!r}" for name in regions if name not in found]
        problems += [f"region {name!r} is not generated by anything" for name in found if name not in regions]
        if problems:
            raise PageError(
                f"{self.path}: {'; '.join(problems)}. Add each region as `<!-- generated: NAME -->` followed by "
                "`<!-- end generated -->` on a later line."
            )

        def replace(m: re.Match[str]) -> str:
            name = m["name"]
            return f"<!-- generated: {name} -->\n\n{regions[name].strip()}\n\n<!-- end generated -->"

        return REGION.sub(replace, text)

    def check(self) -> list[str]:
        """The unified diff between the page and its regenerated form; empty when it is up to date."""
        current = (ROOT / self.path).read_text()
        wanted = self.fill(current)
        if current == wanted:
            return []
        return list(
            difflib.unified_diff(
                current.splitlines(), wanted.splitlines(), str(self.path), "generated", lineterm="", n=1
            )
        )

    def write(self) -> bool:
        """Regenerate the page; return whether it changed."""
        path = ROOT / self.path
        current = path.read_text()
        wanted = self.fill(current)
        if current == wanted:
            return False
        _ = path.write_text(wanted)
        return True


def cell(text: str) -> str:
    """Plain text made safe for a Markdown table cell on the documentation site."""
    text = re.sub(r"\s+", " ", text)
    for char, escaped in (("\\", "\\\\"), ("|", "\\|"), ("*", "\\*"), ("<", "&lt;"), ("{{", "{{ '{{' }}")):
        text = text.replace(char, escaped)
    return text


def code(text: str) -> str:
    """Inline code for a table cell, with a fence long enough for backticks in `text`."""
    fence = "`" * (max((len(run) for run in re.findall(r"`+", text)), default=0) + 1)
    pad = " " if text.startswith("`") or text.endswith("`") else ""
    # GFM splits table cells on every unescaped pipe, even inside code spans.
    return f"{fence}{pad}{text}{pad}{fence}".replace("|", "\\|")


# Words of plain-text help that are code: options, $VARIABLES, paths, file names and identifiers.
CODE_WORD = re.compile(
    r"""(?<![\w`$/.-])(?!and/or\b)(
        https?://\S+[^\s.,;:)]
      | --[a-z][a-z0-9-]*
      | \$[A-Z_][A-Z0-9_]*
      | (?:[A-Za-z0-9_.*-]*/)+[A-Za-z0-9_.*-]*
      | [A-Za-z0-9_-]+\.(?:json|ya?ml|md|toml|sh|py)
      | [a-z][a-z0-9]*(?:_[a-z0-9]+)+(?:\.[a-z][a-z0-9_]+)*
      | [a-z][a-z0-9_]+\.[a-z][a-z0-9_]+
      | [A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+
    )(?<![.])(?![\w`/])""",
    re.VERBOSE,
)


def prose(text: str) -> str:
    """Plain text, such as a --help string, as a table cell with its code words in code spans."""
    parts: list[str] = []
    last = 0
    text = " ".join(text.split())
    for m in CODE_WORD.finditer(text):
        parts += [cell(text[last : m.start()]), code(m[1])]
        last = m.end()
    parts.append(cell(text[last:]))
    return "".join(parts)


def table(header: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join(lines)
